---

- name:  Zabbix Agent2 deploy for DOcker MOnitoring
  hosts: redhat


  pre_tasks:
   - name: Instalar llave GPG
     ansible.builtin.rpm_key:
      key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD
      state: present
     tags: 
     - hecho

  tasks:
   - name: Instalar repositorio zabbix
     ansible.builtin.yum:
      name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
      state: present
     tags: 
     - hecho

   - name: Instalar Zabbix Agent2
     ansible.builtin.yum:
      name: zabbix-agent2
      state: present
     tags: 
     - hecho
  
   - name: Copiar archivo de configuracion zabbix-agent2
     ansible.builtin.copy:
      src: zabbix_agent2.conf
      dest: /etc/zabbix

   - name: Habilitar systemD en zabbix-agent2 para cada inicio
     ansible.builtin.command:
      cmd: systemctl enable zabbix-agent2

   - name: Reiniciar el servicio zabbix-agent2 para efectuar cambios en archivo de configuracion
     ansible.builtin.command:
      cmd: systemctl restart zabbix-agent2
   
   - name: Visualizar resultado de reinicio de agente
     ansible.builtin.command:
      cmd: systemctl status zabbix-agent2
     register: status
    
   - name: Print status
     ansible.builtin.debug:
      msg: "{{status}}"
      