---
# tasks file for zabbix-role


#Instalación y configuración de Zabbix Agent2 para monitoreo de Docker
  - name: Instalar llave GPG
    ansible.builtin.rpm_key:
      key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD
      state: present
    tags: 
     - hecho


  - name: Instalar repositorio zabbix
    ansible.builtin.yum:
      name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
      state: present
    tags: 
     - hecho

  - name: Instalar Zabbix Agent2
    ansible.builtin.yum:
      name: zabbix-agent2
      state: present
    tags: 
     - hecho
  
  - name: Copiar archivo de configuracion zabbix-agent2
    ansible.builtin.copy:
      src: zabbix_agent2.conf
      dest: /etc/zabbix
    tags: 
     - hecho

  - name: Habilitar systemD en zabbix-agent2 para cada inicio
    ansible.builtin.command:
      cmd: systemctl enable zabbix-agent2
    tags: 
     - hecho

  - name: Reiniciar el servicio zabbix-agent2 para efectuar cambios en archivo de configuracion
    ansible.builtin.command:
      cmd: systemctl restart zabbix-agent2
    tags: 
     - hecho

  - name: Ejecutar reinicio de agente zabbix
    ansible.builtin.command:
      cmd: systemctl status zabbix-agent2
      register: status
    tags:
     - hecho

    
  - name: Visualizar el resultado del reinicio de agente zabbix
    ansible.builtin.debug:
      msg: "{{status.stdout_lines}}"
    tags:
     - hecho

  - name: Agregar usuario Zabbix a grupo Docker 
    ansible.builtin.command:
      cmd: usermod -a -G docker zabbix
    tags:
     - hecho

  - name: Obtener informacion sobre grupos
    ansible.builtin.command:
      cmd: cat /etc/group
    register: zabbix
    tags:
     - hecho

  - name: Visualizar si el usuario zabbix pertenece al grupo docker
    ansible.builtin.debug:
      msg: "{{zabbix.stdout_lines[58]}}"
    tags:
    - hecho

  - name: Setear variables de conexion
    ansible.builtin.set_fact:
      delegate_to: 'http://zabbix-server:8080'
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_use_ssl: false
      ansible_httpapi_validate_certs: false
      ansible_zabbix_url_path: ""
      ansible_httapi_port: 8080
      ansible_user: Admin 
      ansible_httpapi_pass: zabbix
      
  
  - name: Verificar conexion
    ansible.builtin.debug:
      msg: "Conexion establecida"


    delegate_to: 'localhost'
  - name: Crear host en zabbix
    community.zabbix.zabbix_hostmacro:
      macro_name: nico
      macro_value: "nito"
      state: present
      host_name: Red Hat Platform Automatization
      visible_name: Red Hat Platform Automatization
      description: Server creado desde Ansible - Contiene Ansible y Docker
      host_groups:
        - Linux servers
      link_templates:
        - Linux by Zabbix agent
      status: enabled
      interfaces:
        - type: 1
          useip: 1
          ip: 192.168.100.69
          port: "10050"

    
